### ISSUE TITLE
Documentation link broken for Webhook AuthZ: https://kubernetes.io/docs/admin/authorization/webhook/

### ISSUE THREAD

**Issue by leogps** [kubernetes/apiserver#10]
The documentation link for Authorization for API Server's via Webhook shows 404.
https://kubernetes.io/docs/admin/authorization/webhook/

This link is referred to here:
https://kubernetes.io/docs/admin/authorization/#authorization-modules

**Comment by vbmade2000** [comment]
@leogps Link is working now. Please check this and close this issue.
