### ISSUE TITLE
k8s 1.7 corresponding release of apiserver

### ISSUE THREAD

**Issue by ash2k** [kubernetes/apiserver#16]
Similar to https://github.com/kubernetes/client-go/issues/231 but for apiserver.

/cc @caesarxuchao

**Comment by ericchiang** [comment]
For synced repos can we just migrate all tags instead of doing this manually every time? E.g. any repos who's source of truth is `k8s.io/kubernetes/staging` automatically get the same tags as kubernetes/kubernetes?

**Comment by caesarxuchao** [comment]
We should automate the process as part of the release process. I haven't looked into details.

I'll find try to find a team to maintain the publishing robot.

**Comment by sttts** [comment]
We tag 1.7 releases now. Closing.

/close
