### ISSUE TITLE
Naming resources for Aggregated APIs

### ISSUE THREAD

**Issue by arschles** [kubernetes/apiserver#17]
The [service-catalog](https://github.com/kubernetes-incubator/service-catalog) system has an aggregated API server that names four resource types:

- `Broker`
- `ServiceClass`
- `Instance`
- `Binding`

The fully-qualified names for these resources are all listed as `*.servicecatalog.k8s.io`, but one may still use the short version in `kubectl`. However, `binding` poses a problem because it conflicts with the core resource name. It is possible to simply use the fully-qualified name, but this conflict raises a bigger question: is there any guidance on naming resources in aggregated API servers, or should there be?

For example, should we tell users to choose resource names that do not conflict with core resource names (I think so)? Are there ways we can suggest for users to make their resource names more descriptive (we have chosen to prefix every name with `ServiceCatalog`, but I hardly think that is the optimal solution)?

**Comment by nilebox** [comment]
Having some way of short scopes as an alternative to fully-qualified namespaced resource names would be useful for Aggregated APIs. For example,
```
kubectl get servicecatalog:binding my-binding
```
where `servicecatalog` is an alias for the API server owning the `binding` resource type.

**Comment by MHBauer** [comment]
Example of fully qualified specification looks like 
```
k get binding.servicecatalog.k8s.io
k get bindings.v1alpha1.servicecatalog.k8s.io --all-namespaces
```
Long and repetitive to type.

Even had we created a type that was unique at the time, there is no guarantee that a future type would not be created in the core with the same name later. (i.e. we created Binding first, but later core apiserver comes along and creates a Binding object)
We basically need ICANN/IANA for types in the kube namespace.

**Comment by nilebox** [comment]
> We basically need ICANN/IANA for types in the kube namespace.

it is not realistic to have a centralized registry of unique resource names in the decentralized Aggregated APIs world.

The only reliable solution provided out of the box is fully qualified namespace, but as you mentioned it's too long and repetitive for manual typing in kubectl. Thus, I would consider and alternative `scope` approach, and discuss what could be the generic scope which works for everyone:
- API server alias/key - simple and directly suits the API Aggregation which is essentially a collection of API servers under proxy umbrella
- hierarchical name resolution (e.g. `bindings`, `servicecatalog.bindings`, `v1alpha1.servicecatalog.bindings` etc)

**Comment by seans3** [comment]
I believe this same conflict dynamic is why TPR does not work with aggregation. The TPR names "binding.servicecatalog.k8s.io", "broker.servicecatalog.k8s.io", etc. overlap with the aggregated API of the same names. While we don't care about TPR, this same problem might also affect CRD.

**Comment by deads2k** [comment]
Partially qualified names are found too, so `kubectl get binding.se` works.  You only need to specify enough to unambiguous.  Scripts should always fully qualify.
