### ISSUE TITLE
Example of a basic API server

### ISSUE THREAD

**Issue by kris-nova** [kubernetes/apiserver#2]
Any way I could request a very basic example of using the library to get a vanilla API server up and running with a hello world? I am working on trying to build one now, and can contribute my notes/examples if that helps.

But wondering if anyone has anything useful lying around that isn't in the repo!

Cheers

**Comment by pmorie** [comment]
@kris-nova we've just built one in service-catalog and have notes to compare - @MHBauer also has a PR open to the community to add docs on how to do this. We definitely need both an example and some technical documentation explaining the process that we maintain as we refactor.

**Comment by pmorie** [comment]
https://github.com/kubernetes/community/pull/309

**Comment by kris-nova** [comment]
Thanks @pmorie I was actually just looking at the one in service catalog.. this is *exactly* what I was looking for! Thanks, and I hope you don't mind if I borrow some ideas from your code!

**Comment by pmorie** [comment]
@kris-nova feel free!

also related: https://github.com/kubernetes/kubernetes/pull/41136

**Comment by MHBauer** [comment]
Be aware that the service-catalog server is using a downlevel version of k8s and that constant refactors in apimachinery mean direct copy and paste may not compile.

**Comment by deads2k** [comment]
kubernetes/kubernetes#41136 is an API server with one resource.  It will always be current since it builds in tree.  Once https://github.com/kubernetes/test-infra/pull/1784 merges, we'll have up to date, matched syncs

**Comment by kargakis** [comment]
https://github.com/kubernetes/sample-apiserver

**Comment by kris-nova** [comment]
Super closed thanks everyone
