### ISSUE TITLE
Add PrepareForDelete to RESTGracefulDeleteStrategy

### ISSUE THREAD

**Issue by staebler** [kubernetes/apiserver#21]
There is a desire in https://github.com/kubernetes-incubator/service-catalog to have a PrepareForDelete function in the RESTGracefulDeleteStrategy interface similar to PrepareForCreate and PrepareForUpdate functions in the RESTCreateStrategy and RESTUpdateStrategy interfaces. When ServiceInstance and ServiceBinding resources are deleted in service-catalog, the user that requested the delete is stored in the resource to be sent to the broker. Currently, service-catalog uses the CheckGracefulDelete function to get the user from the context to add it to the resource. That does not seem like an appropriate use of that function.

**Comment by deads2k** [comment]
We get the object in storage to decide whether it is immediately deleted already.  I don't object to adding an injection point, but without a finalizer the object could deleted straight away.

@kubernetes/sig-api-machinery-feature-requests

**Comment by staebler** [comment]
Immediate deletion is not an issue as far as service-catalog is concerned. We add a finalizer. We would not be using the injection point as a means of postponing deletion.
