### ISSUE TITLE
Implement object interface in the swagger spec.

### ISSUE THREAD

**Issue by brendandburns** [kubernetes/apiserver#23]
Context:
https://github.com/kubernetes-client/java/issues/101

See: https://apihandyman.io/writing-openapi-swagger-specification-tutorial-part-4-advanced-data-modeling/#create-a-hierarchy-between-definitions-to-implement-inheritance-highly-experimentatl

for details.

**Comment by davidxia** [comment]
@brendandburns hey, just wondering if there's been any progress on this. I'd love to help if no one's currently working on it. Just gotta know where to start.
