### ISSUE TITLE
Ability to run a fake api server

### ISSUE THREAD

**Issue by kargakis** [kubernetes/apiserver#25]
I would like to run a fake api server that supports declaring actions in its handlers so I can test various scenarios as part of integration testing in prow. Is this possible today (I guess not)? Is this the correct repository to request such a thing?

@kubernetes/sig-api-machinery-feature-requests

**Comment by vimalk78** [comment]
s this possible today ?

**Comment by yuanyp8** [comment]
any update?

**Comment by lavalamp** [comment]
There are fake clients which support some variation of this request.

Alternatively you can run webhooks to do things for you in an e2e test scenario.

There are no further plans along these lines at the moment.
