### ISSUE TITLE
Keystone endpoint is enforced to use https

### ISSUE THREAD

**Issue by resouer** [kubernetes/apiserver#26]
May I ask why it is enforced to use https here:
https://github.com/kubernetes/apiserver/blob/master/plugin/pkg/authenticator/password/keystone/keystone.go#L76

cc @ixdy

**Comment by ixdy** [comment]
I don't know why you cc'd me, but it's been that way for years (https://github.com/kubernetes/kubernetes/pull/11798).

cc @uruddarraju

**Comment by ixdy** [comment]
see also https://github.com/kubernetes/kubernetes/pull/38464

**Comment by resouer** [comment]
So the reason seems to be: https://github.com/kubernetes/kubernetes/pull/38464#issuecomment-266419971
