### ISSUE TITLE
DestroyFunc is not exposed via rest.Storage nor called by the ApiServer

### ISSUE THREAD

**Issue by n3wscott** [kubernetes/apiserver#30]
It becomes impossible to call the `DestroyFunc` passed into the registry.Store struct after registering this storage into the `genericAPIServer.InstallAPIGroup()` method.

This is either a bug with the api server, or a misunderstanding on the implementers side for whose responsibility it is to call `DestroyFunc`. 

I propose as a first step, implement a method to `registry.Store`  that allows the `DestroyFunc` to be invoked and add a new interface to `rest.Storage` that allows access to that new method.

Then later we can talk about how the shutting down of the api server should know to call the new method. 

Relates to:
https://github.com/kubernetes/kubernetes/pull/50690
https://github.com/kubernetes/kubernetes/issues/53617
https://github.com/kubernetes-incubator/service-catalog/issues/1649

**Comment by n3wscott** [comment]
I am working on a patch to add the proposed solution.

**Comment by MHBauer** [comment]
I've come to the same conclusion. I'd like to see what you come up with, and if there is any opinion from upstream sig-api.

**Comment by sttts** [comment]
We are aware of a missing shutdown story. Compare https://github.com/kubernetes/kubernetes/pull/50690 for a try to add that.

Without knowing your code, why can't you call the DestroyFunc manually. After all you have all the plumbing under your control. Compare https://github.com/kubernetes/kubernetes/pull/53586/files#diff-2f720a7e61a4ddfcfe9a9e353be8784bR267 for CRDs.

**Comment by MHBauer** [comment]
We can call it, but it has to be threaded fwd and backward and doesn't seem to fully mitigate outstanding threads by the end. Not sure if it requires some time to quiesce.

**Comment by MHBauer** [comment]
Maybe we should all be following along in https://github.com/kubernetes/kubernetes/issues/49489 ?

**Comment by n3wscott** [comment]
Thanks, we still are needing to work around this.
