### ISSUE TITLE
MutatingWebHook Configuration Changing Name of Resource

### ISSUE THREAD

**Issue by rawkode** [kubernetes/apiserver#38]
Hey,

I've been working on a MutatingWebHookConfiguration that modifies the name of a resource (Only on CREATE, I know it's immutable beyond that), depending on the metadata. I'm happy to get into the use-case, if we feel it's pertinent to provide more context.

The problem is, when the next CREATE comes in, I want to modify the name again and UPDATE the existing resource. Is it / will it be possible to "upgrade", for lack of a better term, a CREATE to an UPDATE during this phase?

**Comment by erictune** [comment]
I would advise you not to do this.  Please.

- References to these objects from other object would not be work.
- apply won't work.
- Not what users expect based on experience with other objects.
- not clear that idempotent creation can work.

**Comment by rawkode** [comment]
Hi @erictune,

I do understand why you say that - but it's in-order to provide blue / green deployment automation from within Kubernetes. I was hoping I could allow developers to deploy as normal, but behind the scenes be creating a new deployment and launching a job (or using an operator) to monitor the new deployment for the configured annotation time and then remove the old deployment

**Comment by rawkode** [comment]
Hmm. Perhaps I could try this another route, and add a new updateStrategy for deployments

**Comment by erictune** [comment]
You can make your own version of Deployment that does what you want.
Here is are two starting points:
- https://github.com/GoogleCloudPlatform/metacontroller
- https://github.com/google/blue-green-deployment-controller

**Comment by rawkode** [comment]
Thanks for your assistance, @erictune :+1:
