### ISSUE TITLE
Not pulling in etcd v3 client as dependency

### ISSUE THREAD

**Issue by tamalsaha** [kubernetes/apiserver#39]
We are using https://github.com/openshift/generic-admission-server to write our webhook. But when we upgraded from kubernetes 1.9 to 1.10 libraries. I noticed that we also now depend on etcd v3 client. It seems to be coming from https://github.com/kubernetes/apiserver/blob/8bb94c1e4658c0759b38483c48c89ae84b9bd571/pkg/server/options/etcd.go#L35

It will be great if webhook authors could avoid this dependency.

**Comment by tamalsaha** [comment]
/sig apimachinery

cc: @deads2k @sttts

**Comment by tamalsaha** [comment]
cc: @lavalamp

**Comment by lavalamp** [comment]
Thanks for the issue, I agree it's good to avoid extra dependencies.

Tagging @deads2k since I'm not sure how much attention folks pay to the issues in this repo (as opposed to the main one).

**Comment by deads2k** [comment]
> Thanks for the issue, I agree it's good to avoid extra dependencies.
> 
> Tagging @deads2k since I'm not sure how much attention folks pay to the issues in this repo (as opposed to the main one).

Extra is relative.  I'd be open trying to associate it with etcd options in a subpackage, but I think that it needs to remain in apiserver.
