### ISSUE TITLE
Deep dive into how Kubernetes REST API works

### ISSUE THREAD

**Issue by devdattakulkarni** [kubernetes/apiserver#41]
I have written a blog post detailing how the Kubernetes REST API works:
https://medium.com/@cloudark/deep-dive-into-how-kubernetes-rest-api-works-517c86f1640b

@pwittrock @sttts Let me know if this is correctly capturing Kubernetes REST API's inner workings.

**Comment by sttts** [comment]
Looks pretty cool. Remembering having done the same investigations two years ago, dejavu :-)
