### ISSUE TITLE
Deprecated/Missing Kubernetes API Server Metrics

### ISSUE THREAD

**Issue by pivotal-matt-staples** [kubernetes/apiserver#59]
It appears that the following Kubernetes apiserver metrics were deprecated, with the old list being the following:

```
apiserver_request_latencies_bucket
apiserver_requests
apiserver_request_count
apiserver_request_errors
apiserver_latency
```

After extensive searches through the documentation, the only deprecated metric I can find from the list is this:

```apiserver_request_count = apiserver_request_total```

As for the others, they do not appear anywhere that I have looked in the Kubernetes code base on github, I had thought that they would be here somehwere, given that this is the page for apiserver, but only the one above is listed. 

The metrics are being used to determine the health of TKGI, with output that used to look like this: 

```
# Recording rule expr
histogram_quantile ( 0.90, sum by (le, verb)( rate(apiserver_request_latencies_bucket[5m]) ) ) / 1e3 > 0
histogram_quantile ( 0.90, sum by (le, job, verb, instance)( rate(apiserver_request_latencies_bucket[5m]) ) ) / 1e3
sum by()(probe_success{provider=\"kubernetes\", component=\"apiserver\"})
sum without (instance)(kubernetes:job_verb_code_instance:apiserver_requests:rate5m)
sum by (job, verb, code, instance)(rate(apiserver_request_count[5m]))
sum without (instance)(kubernetes:job_verb_code_instance:apiserver_requests:ratio_rate5m)
kubernetes:job_verb_code_instance:apiserver_requests:rate5m / ignoring(verb, code) group_left sum by (job, instance)(kubernetes:job_verb_code_instance:apiserver_requests:rate5m)
sum by (job)(kubernetes:job_verb_code_instance:apiserver_requests:ratio_rate5m{verb=~\"GET|POST|DELETE|PATCH\", code=~\"5..\", cluster=\"$cluster\"})
histogram_quantile ( 0.90, sum by (le, job)( rate(apiserver_request_latencies_bucket{verb=~\"GET|POST|DELETE|PATCH\", cluster=\"$cluster\"}[5m]) ) ) / 1e3
kubernetes:job:apiserver_request_errors:ratio_rate5m < bool 0.01 * kubernetes::job:apiserver_latency:pctl90rate5m < bool 200
kubernetes:job:apiserver_request_errors:ratio_rate5m < bool Inf * kubernetes::job:apiserver_latency:pctl90rate5m < bool Inf
```

Any help from anyone on this would be greatly appreciated, we would like to know what happened to these metrics OR where they are stored. 

Thanks

**Comment by Wang-Kai** [comment]
Anyone know about it ?

**Comment by dims** [comment]
deprecated ones have been removed. please see what is generated now:
https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/documentation.md

**Comment by Wang-Kai** [comment]
> 

Thank you so much !

**Comment by Wang-Kai** [comment]
> deprecated ones have been removed. please see what is generated now: https://github.com/kubernetes/kubernetes/blob/master/test/instrumentation/documentation/documentation.md

Thank you so much !
