### ISSUE TITLE
no json naming on audit.Event object

### ISSUE THREAD

**Issue by LiorAlafiArmo** [kubernetes/apiserver#64]
Hi, from k8s I've requested audit events and got an object

`   {
            "kind": "Event",
            "apiVersion": "audit.k8s.io/v1",
            "level": "Metadata",
            "auditID": "1847e1e1-d66b-4661-b458-4dc553cd8539",
            "stage": "ResponseComplete",
            "requestURI": "/apis/storage.k8s.io/v1?timeout=32s",
            "verb": "get",
            "user": {
                "username": "system:serviceaccount:kube-system:generic-garbage-collector",
                "uid": "83093a4c-3f5f-433e-8fd4-4a2cc23eead8",
                "groups": [
                    "system:serviceaccounts",
                    "system:serviceaccounts:kube-system",
                    "system:authenticated"
                ]
            },
            "sourceIPs": [
                "192.168.49.2"
            ],
            "userAgent": "kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/af46c47/system:serviceaccount:kube-system:generic-garbage-collector",
            "responseStatus": {
                "metadata": {},
                "code": 200
            },
            "requestReceivedTimestamp": "2021-02-18T08:28:43.237861Z",
            "stageTimestamp": "2021-02-18T08:28:43.238551Z",
            "annotations": {
                "authentication.k8s.io/legacy-token": "system:serviceaccount:kube-system:generic-garbage-collector",
                "authorization.k8s.io/decision": "allow",
                "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"system:discovery\" of ClusterRole \"system:discovery\" to Group \"system:authenticated\""
            }
        }`

yet when I marshal  and unmarshal it i get the fields in PascalCase instead of camelCase
I saw that audit.Event (/pkg/apis/audit/types.go) has no json names

this creates anomality between data received from k8s and data received from golang package.

`{
    "kind": "Event",
    "apiVersion": "audit.k8s.io/v1",
    "Level": "Metadata",
    "AuditID": "1847e1e1-d66b-4661-b458-4dc553cd8539",
    "Stage": "ResponseComplete",
    "RequestURI": "/apis/storage.k8s.io/v1?timeout=32s",
    "Verb": "get",
    "User": {
    "username": "system:serviceaccount:kube-system:generic-garbage-collector",
    "uid": "83093a4c-3f5f-433e-8fd4-4a2cc23eead8",
    "groups": [
    "system:serviceaccounts",
    "system:serviceaccounts:kube-system",
    "system:authenticated"
    ]
    },
    "ImpersonatedUser": null,
    "SourceIPs": [
    "192.168.49.2"
    ],
    "UserAgent": "kube-controller-manager/v1.20.0 (linux/amd64) kubernetes/af46c47/system:serviceaccount:kube-system:generic-garbage-collector",
    "ObjectRef": null,
    "ResponseStatus": {
    "metadata": {},
    "code": 200
    },
    "RequestObject": null,
    "ResponseObject": null,
    "RequestReceivedTimestamp": "2021-02-18T08:28:43.237861Z",
    "StageTimestamp": "2021-02-18T08:28:43.238551Z",
    "Annotations": {
    "authentication.k8s.io/legacy-token": "system:serviceaccount:kube-system:generic-garbage-collector",
    "authorization.k8s.io/decision": "allow",
    "authorization.k8s.io/reason": "RBAC: allowed by ClusterRoleBinding \"system:discovery\" of ClusterRole \"system:discovery\" to Group \"system:authenticated\""
    }
    }`

**Comment by lavalamp** [comment]
Please open an issue on the main repo and tag sig auth.

**Comment by njuptlzf** [comment]
The internal version(`staging/src/k8s.io/apiserver/pkg/apis/audit/types.go`) is used internally by apiserver.
Codec can use external version(such as `staging/src/k8s.io/apiserver/pkg/apis/audit/v1/types.go`)
