### ISSUE TITLE
Update go-restful module to version >= 3.8.0 due to security issues

### ISSUE THREAD

**Issue by rsvalerio** [kubernetes/apiserver#87]
Hi all!

I saw [this commit](https://github.com/kubernetes/apiserver/commit/30571358f578eabf5ca12499543c50c4b1263653) updating go-restful to version 3.7.5 for the next release.

Would it be possible to update it to something >= 3.8.0?

I'm asking because of [this security issue](https://github.com/kubernetes-sigs/descheduler/issues/897#issue-1326061625) trivy found

Thanks in advance.

**Comment by damemi** [comment]
You might want to open this issue against github.com/kubernetes/kubernetes, the code in this repo is just synced from there so I don't think issues in this repo get much attention
