### ISSUE TITLE
EOL Component

### ISSUE THREAD

**Issue by satish-suradkar** [kubernetes/apiserver#90]
```
Here is the list of policies natefinch/lumberjack v2.0.0 violates.
Version/Branch EOL
Severity:Major

Category:Security

Scan Modes:Full

Description
Version or branch requested is EOL.   Please update to a supported version.

Conditions
Component Version Approval StatusEQUALS Deprecated
Component UsageNOT EQUAL TO Dev. Tool / Excluded
```
natefinch/lumberjack v2.0.0 is EOL. Any plant to update it ?

**Comment by nikhita** [comment]
The maintainer of lumberjack is active in the repo. I've created https://github.com/natefinch/lumberjack/pull/175 to fix CVEs in lumberjack's dependencies (`gopkg.in/yaml.v2)`...aAlthough they don't really affect kubernetes beacause k8s uses a newer version of `gopkg.in/yaml.v2`.

Once that PR gets merged, we can bump to a newer patch version of `natefinch/lumberjack` and that'll get rid of the EOL warnings when a scan is run.
