### ISSUE TITLE
Query on ContinueToken

### ISSUE THREAD

**Issue by mehvaibh** [kubernetes/apiserver#95]
Hello,
I have a query on comment of `continueToken` struct. 

> // continueToken is a simple structured object for encoding the state of a continue token.
// TODO: if we change the version of the encoded from, we can't start encoding the new version
// until all other servers are upgraded (i.e. we need to support rolling schema)
// This is a public API struct and cannot change.
type continueToken struct {
	APIVersion      string `json:"v"`
	ResourceVersion int64  `json:"rv"`
	StartKey        string `json:"start"`
}
https://github.com/kubernetes/apiserver/blob/master/pkg/storage/continue.go#L35-L43

I wanted to check on above comment specially  "This is a public API struct and cannot change." 

It seems like this structure in Marshaled/UnMarshaled using [json econding](https://pkg.go.dev/encoding/json#Marshal) and from the doc it seems adding a new field to struct is backward compatible.

I tried testing this by adding a new field to this `continueToken`. The token generated by new API Server (with new extra field) is parsable by old API server and vice versa. This makes adding new field in this struct both roll-forward and roll-back compatible. 

As I may not know all the details and use cases for this token other than it is primarily used to encode ETCD related meta data like key prefix, revision number etc (sorry If i missed critical details).
So wanted to confirm is this the only restriction to enforce no changes or there are some other use cases which I missed(thanks for enlightening me in this case)

**Comment by mehvaibh** [comment]
@stevekuznetsov @logicalhan  tagging you folks since I see you have commit history on this file :).(sorry if I mistagged, pls help tag right folks who may know some context on this)

**Comment by stevekuznetsov** [comment]
@mehvaibh could you provide some more details for what you are trying to achieve? The purpose of the `ContinueToken` is to encode how far along a LIST call is during pagination, so that the process is stateless on the server. During a paginated call, the server encodes where it left off in the last request into the `ContinueToken` and a client passes that token back, verbatim, in the `?continue=` query parameter on their next call. The `StartKey` is used to drive the next paginated call.

**Comment by mehvaibh** [comment]
Thanks for reply @stevekuznetsov !

My query is regarding this comment on `continueToken`
> "This is a public API struct and cannot change."

I'm evaluating adding one more param to this struct (can discuss more if required afterwards) but above comments suggests this `continueToken` struct should not be changed(pls correct me if I misunderstood). 
My query is can we add a new param to this struct ?

Based on my testing (explained in detailed in previous comment) adding a new param does not break compatibility.

**Comment by stevekuznetsov** [comment]
It would have to follow the same rules as any other public-facing API. If the behavior degrades gracefully with old servers perhaps it's OK, but I would suggest you write up a KEP for the change and get feedback from the API Machinery SIG as a whole.
